#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

WORKDIR=$(pwd)
SCRIPTDIR=$(cd "$(dirname "$0")" && pwd)

print_usage()
{
    cat <<EOF
Convert a LXD image into a Raspberry Pi image.

Required arguments:
 -i FILE, --input=FILE              : LXD container archive that contains the root file system.
 -o FILE, --output=FILE             : Name of the file that will contain the resulting Raspberry Pi image.
Optional arguments:
 -h, --help                         : Print help text.
 -w DIRECTORY, --workdir=DIRECTORY  : Working directory.
EOF
    return 0
}

if ! options=$(getopt -o hi:o:w: -l help,input:,output:,workdir: -- "$@")
then
    print_usage
    >&2 echo "Error: Invalid option."
fi
eval set -- "$options"

while true
do
    case "$1" in
        -h|--help)          print_usage && exit 0;;
        -i|--input)         INPUT_ARCHIVE=$2; shift 2;;
        -o|--output)        OUTPUT_ARCHIVE=$2; shift 2;;
        -w|--workdir)       WORKDIR=$2; shift 2;;
        *)                  break ;;
    esac
done

TEMPDIR=$(mktemp -p ${WORKDIR} -d -t tmp.XXXXXXXX)
echo ${TEMPDIR}
