#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

GITOPS_USER_NAME="{{ gitops_user_name }}"
GITOPS_USER_GROUP_NAME="{{ gitops_user_group_name }}"
GITOPS_USER="sudo -u ${GITOPS_USER_NAME}"
WORKDIR="/home/${GITOPS_USER_NAME}"

print_error()
{
    local MESSAGE="${1}"
    >&2 echo -e "${0}: Error: ${MESSAGE}"
}

unexpected_exit()
{
    local TEMPDIR="${1}"
    print_error "Going to clean up after abnormal script termination."
    clean_up "${TEMPDIR}"
    trap - EXIT
    exit 3
}

clean_up()
{
    local TEMPDIR="${1}"
    ${GITOPS_USER} rm -rf "${TEMPDIR}"
}

if [ $# -ne 1 ]
then
    print_error "This script is expecting exactly one argument (the configuration file)."
    exit 2
fi

CONFIG="$1"

if [ ! -e "${CONFIG}" ]
then
    print_error "The configuration file ${CONFIG} does not exist."
    exit 1
fi

if [ ! -s "${CONFIG}" ]
then
    print_error "The configuration file ${CONFIG} is empty."
    exit 1
fi

if ! jq -e . >/dev/null 2>&1 < "${CONFIG}"
then
    print_error "Failed to parse ${CONFIG}."
    exit 1
fi

if ! PLAYBOOK_URL="$(jq -r -e .playbook_url < "${CONFIG}")"
then
    echo "${0}: Nothing to do as there is no 'playbook_url'."
    exit 0
fi

if ! PLAYBOOK_VERSION="$(jq -r -e .playbook_version < "${CONFIG}")"
then
    echo "${0}: Nothing to do as there is no 'playbook_version'."
    exit 0
fi

if ! EXPECTED_OS_IMAGE="$(jq -r -e .expected_os_image < "${CONFIG}")"
then
    echo "${0}: Skipping OS image check!"
else
    CURRENT_OS_IMAGE=$(cut -d'=' -f2 < /etc/mender/artifact_info)
    if [ "${CURRENT_OS_IMAGE}" != "${EXPECTED_OS_IMAGE}" ]
    then
        print_error "The current OS image (${CURRENT_OS_IMAGE}) does not match the expected one (${EXPECTED_OS_IMAGE})!"
        echo "${0}: Possible reason: The previous OS image deployment failed."
        exit 1
    fi
fi

PLAYBOOK_SOURCE_IS_GIT="false"
GIT_URL_REGEX='^(https://|git@|ssh://).*'
if [[ ${PLAYBOOK_URL} =~ ${GIT_URL_REGEX} ]]
then
    PLAYBOOK_SOURCE_IS_GIT="true"
fi

TEMPDIR=$(${GITOPS_USER} mktemp -p "${WORKDIR}" -d -t .tmp.XXXXXXXX)
trap 'unexpected_exit "${TEMPDIR}"' EXIT

CONFIG_FILE="${TEMPDIR}"/$(basename -- "${CONFIG}")
cp "${CONFIG}" "${CONFIG_FILE}"
chown "${GITOPS_USER_NAME}":"${GITOPS_USER_GROUP_NAME}" "${CONFIG_FILE}"

DEBIAN_FRONTEND=noninteractive apt-get update > /dev/null

if [ "${PLAYBOOK_SOURCE_IS_GIT}" == "true" ]
then
    DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends -y install git > /dev/null
    cd "${TEMPDIR}"
    ${GITOPS_USER} GIT_TERMINAL_PROMPT=0 git clone -c advice.detachedHead=false --branch "${PLAYBOOK_VERSION}" --depth 1 "${PLAYBOOK_URL}" playbook > /dev/null

    ROLES_PATH="${TEMPDIR}/playbook/roles"
    ${GITOPS_USER} mkdir -p "${ROLES_PATH}"
    cd "${TEMPDIR}/playbook"

    if [ -e requirements.yml ]
    then
        ${GITOPS_USER} ansible-galaxy install --roles-path "${ROLES_PATH}" -r requirements.yml
    fi
else
    # there is no VERSION_ID in testing
    VERSION_ID="99"
    source /etc/os-release

    PLAYBOOK_PACKAGE="${PLAYBOOK_URL}"
    apt-mark unhold "${PLAYBOOK_PACKAGE}" || true
    DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends -y install "${PLAYBOOK_PACKAGE}=${PLAYBOOK_VERSION}+deb${VERSION_ID//./}" > /dev/null
    apt-mark hold "${PLAYBOOK_PACKAGE}"
    cd "/usr/share/${PLAYBOOK_PACKAGE}"
fi

${GITOPS_USER} ansible-playbook --connection=local --inventory 127.0.0.1, playbook.yml --extra-vars "@${CONFIG_FILE}" 1>&2

clean_up "${TEMPDIR}"

trap - EXIT

if ! PLAYBOOK_NEEDS_REBOOT="$(jq -r -e .playbook_needs_reboot < "${CONFIG}")"
then
    exit 0
else
    if [ "${PLAYBOOK_NEEDS_REBOOT}" == "true" ]
    then
        exit 20
    else
        exit 0
    fi
fi
