#!/bin/bash

# This identity script returns the MAC address of {{ 'end0' if mender_device_type == 'pi4-v3' else 'eth0' }} as the device identity.

set -ue

MAC_FILE=/sys/class/net/{{ 'end0' if mender_device_type == 'pi4-v3' else 'eth0' }}/address

if [ ! -f "${MAC_FILE}" ]
then
    >&2 echo "Error: ${MAC_FILE} not found!"
    exit 1
fi

echo "mac=$(cat ${MAC_FILE})"
