#!/bin/bash
# Copyright 2022 Northern.tech AS
# Copyright 2022 Matthias Luescher
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

set -o errexit
set -o nounset

CONFIG=${TEST_CONFIG:-/var/lib/mender-configure/device-config.json}
APPLY_DIR=${TEST_APPLY_DIR:-/usr/lib/mender-configure/apply-device-config.d}

# Primarily used by tests, but can be enabled by anyone.
QUIET=${QUIET:-0}

apply_scripts() {
    global_return_code=0
    for script in "$APPLY_DIR"/*; do
        if [ "$script" = "$APPLY_DIR/*" ]; then
            # No files present, glob failed and returned verbatim '*'.
            exit 0
        fi

        if [ "$QUIET" = 0 ]; then
            echo "Executing $script"
        fi
        return_code=0
        "$script" "$CONFIG" || return_code=$?
        if [ $return_code -ne 0 ]; then
            # Set the overall return code, but prioritize real errors over
            # "reboot return code" (20).
            if [ $return_code -ne 20 ] || [ $global_return_code -eq 0 ]; then
                global_return_code=$return_code
            fi
            echo "Script \"$script\" returned exit code $return_code." 1>&2
        fi
    done

    return $global_return_code
}

if [ ! -f "${CONFIG}" ]; then
    exit 0
fi

RET=0
apply_scripts || RET=$?
if [ $RET -eq 20 ]; then
    touch "/var/run/reconfiguration-requests-device-reboot"
    exit 0
else
    exit $RET
fi